# **Primera entrega del proyecto final**

## **Instrucciones:** 
Abrir el proyecto, nueva terminal
Ejecutar:  npm install   (la primera vez) 
Ejecutar:  nodemon src/index.js

-->sale por consola: Servidor arriba y escuchando puerto 8080!!

Entrar a localhost:8080 en el navegador

*Ejemplos:* 
http://localhost:8080/api/products
http://localhost:8080/api/products/2
http://localhost:8080/api/products?limit=3
